
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: todo
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - todo_db:/var/lib/postgresql/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5141:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=todo;Username=postgres;Password=postgres;Port=5432
      - CorsOrigins=http://frontend:3000,http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8080
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5141
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  todo_db:

networks:
  todo-network:
    driver: bridge
