


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: todo
      POSTGRES_USER: postgres
    ports:
      - 5000:5432
    volumes:
      - todo_db:/var/lib/postgresql/data

volumes:
  todo_db:
